name: build-kernel

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * *"
  pull_request:
  workflow_dispatch:

env:
  CROSS_COMPILE: riscv64-linux-gnu-
  ARCH: riscv
  KBUILD_BUILD_USER: deepin-riscv-sig
  KBUILD_BUILD_HOST: deepin-riscv-builder
  KDEB_COMPRESS: xz
  KDEB_CHANGELOG_DIST: unstable
  OUT_DIR: out
  email: deepin-riscv@deepin.org

permissions:
  pull-requests: read

jobs:
  build-kernel:
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: lpi4a
            kernel_branch: lpi4a-dev
            kernel_git: https://github.com/revyos/thead-kernel
            kernel_config: revyos_defconfig

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Deps"
        run: |
          sudo apt update
          sudo apt install -y gdisk dosfstools g++-12-riscv64-linux-gnu build-essential \
                        libncurses-dev gawk flex bison openssl libssl-dev \
                        dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf mkbootimg \
                        fakeroot genext2fs genisoimage libconfuse-dev mtd-utils mtools qemu-utils qemu-utils squashfs-tools \
                        device-tree-compiler rauc simg2img u-boot-tools f2fs-tools arm-trusted-firmware-tools swig
          sudo update-alternatives --install /usr/bin/riscv64-linux-gnu-gcc riscv64-gcc /usr/bin/riscv64-linux-gnu-gcc-12 10
          sudo update-alternatives --install /usr/bin/riscv64-linux-gnu-g++ riscv64-g++ /usr/bin/riscv64-linux-gnu-g++-12 10
          git config --global user.email $email
          git config --global user.name $KBUILD_BUILD_USER
      - name: "Clone Kernel"
        run: git clone --depth=1 -b ${{ matrix.kernel_branch }} ${{ matrix.kernel_git }} kernel

      - name: "Compile kernel"
        run: |
          pushd kernel
            make CROSS_COMPILE=${CROSS_COMPILE} ARCH=${ARCH} ${{ matrix.kernel_config }}
            if [ -f ../config/${board}/kernelconfig ]; then
              cp -v ../config/${board}/kernelconfig .config
            fi
                        
            sed -i '/CONFIG_LOCALVERSION_AUTO/d' .config && echo "CONFIG_LOCALVERSION_AUTO=n" >> .config
            make CROSS_COMPILE=${CROSS_COMPILE} ARCH=${ARCH} bindeb-pkg -j$(nproc) LOCALVERSION="-${{ matrix.board }}"
          popd
      - name: 'Upload Kernel Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: kernel-${{ matrix.board }}-deb
          path: "*.deb"
          retention-days: 3
